/* ===========================================================
   REFORMA TRIBUTÁRIA (RTC) - PACOTE COMPLETO PARA FIREBIRD 
   cClassTrib - Modelagem + Funções + Procedures + Exemplos
   -----------------------------------------------------------
   Componentes:
     1) Tabela oficial: CCLASSTRIB_OFICIAL (espelho RFB)
     2) Tabelas de negócio: TOP, PRODUTO, TOP_PRODUTO, NCM_NBS_CCLASSTRIB
     3) Funções utilitárias: VALIDA_VIGENCIA, VALIDA_MODELO
     4) Procedure auxiliar:  VALIDA_CCLASSTRIB
     5) Procedure para obter o cClassTrib: RESOLVE_CCLASSTRIB
     5) Procedure para procurar o cClassTrib pelo NCM_NBS: CCLASSTRIB_POR_NCM_NBS
        -----------------------------------------------------------
   Política:
     - Sem hardcode de regra — tudo orientado por dados.
     - Se nada casar, RESOLVE_CCLASSTRIB retorna NULL e o chamador decide
       (usar '000001' ou lançar exception).
   =========================================================== */


/* CREATE DOMAINS */
CREATE DOMAIN RTC_CCLASSTRIB_C AS CHAR(6) CHARACTER SET ISO8859_1 COLLATE PT_BR;
CREATE DOMAIN RTC_CST_C AS CHAR(3) CHARACTER SET ISO8859_1 COLLATE PT_BR;
CREATE DOMAIN RTC_NCM_NBS_C AS CHAR(9) CHARACTER SET ISO8859_1 COLLATE PT_BR;
CREATE DOMAIN RTC_PERCENTUAL AS NUMERIC(7,4);


/* =========================
   1) TABELA OFICIAL (espelho)
   ========================= */
CREATE TABLE RTC_CCLASSTRIB (
    CCLASSTRIB           RTC_CCLASSTRIB_C,   -- ex.: '200003'
    CST_IBSCBS           RTC_CST_C,              -- CST-IBS/CBS
    DESCR_CST_IBSCBS     VCDESCRICAO255,             -- Descrição CST-IBS/CBS
    NOME_CCLASSTRIB      VCDESCRICAO255,             -- Nome cClassTrib
    DESCR_CCLASSTRIB     BLOB SUB_TYPE TEXT,       -- Descrição completa
    LC_REDACAO           BLOB SUB_TYPE TEXT,       -- Redação (LC)
    LC_214_25            BLOB SUB_TYPE TEXT,       -- Referência LC 214/25
    TIPO_ALIQUOTA        VCDESCRICAO50,              -- Tipo da alíquota
    PREDIBS              RTC_PERCENTUAL,             -- Redução IBS (%)
    PREDCBS              RTC_PERCENTUAL,             -- Redução CBS (%)
    IND_REDUCAO_BC       SMALL,                 -- 0/1
    IND_GTRIB_REGULAR    SMALL,
    IND_GCRED_PRESOPER   SMALL,
    IND_GMONO_PADRAO     SMALL,
    IND_GMONO_RETEN      SMALL,
    IND_GMONO_RET        SMALL,
    IND_GMONO_DIF        SMALL,
    IND_GESTORNO_CRED    SMALL,
    CREDITO_PARA         BLOB SUB_TYPE TEXT,
    DINIVIG              DT,                     -- Início vigência
    DFIMVIG              DT,                     -- Fim vigência
    DATA_ATUALIZACAO     DT,
    IND_NFE_ABI          SMALL,
    IND_NFE              SMALL,
    IND_NFCE             SMALL,
    IND_CTE              SMALL,
    IND_CTEOS            SMALL,
    IND_BPE              SMALL,
    IND_BPETA            SMALL,
    IND_BPETM            SMALL,
    IND_NF3E             SMALL,
    IND_NFSE             SMALL,
    IND_NFSE_VIA         SMALL,
    IND_NFCOM            SMALL,
    IND_NFAG             SMALL,
    IND_NFGAS            SMALL,
    IND_DERE             SMALL,
    ANEXO                VCDESCRICAO50,
    LINK                 VCDESCRICAO512,
	
	CONSTRAINT PK_RTC_CCLASSTRIB PRIMARY KEY (CCLASSTRIB) USING INDEX PK_RTC_CCLASSTRIB
);
CREATE INDEX IX_RTC_CCLASSTRIB_VIG ON RTC_CCLASSTRIB (DINIVIG, DFIMVIG);


/* =========================
   2) Tabelas de Negócio
   ========================= */
CREATE TABLE RTC_PARTICIPANTE (
  ID INTEIRO,
  DESCRICAO  VCDESCRICAO100 NOT NULL,
  
  CONSTRAINT PK_RTC_PARTICIPANTE PRIMARY KEY (ID) USING INDEX PK_RTC_PARTICIPANTE
);
CREATE SEQUENCE GEN_RTC_PARTICIPANTE_ID;


CREATE TABLE RTC_OPERACOES (
  ID         INTEIRO,
  DESCRICAO  VCDESCRICAO100,
  CCLASSTRIB RTC_CCLASSTRIB_C,
  
  CONSTRAINT PK_RTC_OPERACOES PRIMARY KEY (ID) USING INDEX PK_RTC_OPERACOES,
  CONSTRAINT FK_RTC_OPERACOES_CCLASSTRIB FOREIGN KEY (CCLASSTRIB) REFERENCES RTC_CCLASSTRIB(CCLASSTRIB) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE SEQUENCE GEN_RTC_OPERACOES_ID;
ALTER SEQUENCE GEN_RTC_OPERACOES_ID RESTART WITH 100;


CREATE TABLE RTC_NCM_CCLASSTRIB (
  ID INTEIRO,
  NCM_NBS      RTC_NCM_NBS_C NOT NULL,
  REGRA    VCDESCRICAO50 NOT NULL,
  PARTICIPANTE INTEIRO DEFAULT 1 NOT NULL,
  TIPO         CSIGLA3 NOT NULL,
  CCLASSTRIB  RTC_CCLASSTRIB_C NOT NULL,
  ANEXO       INTEIRO,
  ARTIGO      INTEIRO,
  
  CONSTRAINT PK_RTC_NCM_CCLASSTRIB PRIMARY KEY (ID) USING INDEX PK_RTC_NCM_CCLASSTRIB,   
  CONSTRAINT UNQ_RTC_NCM_CCLASSTRIB UNIQUE (NCM_NBS, REGRA, PARTICIPANTE),
  CONSTRAINT FK_NCM_NBS_CCT_PARTICIPANTE FOREIGN KEY (PARTICIPANTE) REFERENCES RTC_PARTICIPANTE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RTC_NCM_CCLASSTRIB_CCLASSTRIB FOREIGN KEY (CCLASSTRIB) REFERENCES RTC_CCLASSTRIB(CCLASSTRIB) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IX_NCM_NBS_CCT_NCM_NBS ON RTC_NCM_CCLASSTRIB (NCM_NBS);
CREATE INDEX IX_NCM_NBS_CCT_REGRA ON RTC_NCM_CCLASSTRIB (REGRA);
CREATE INDEX IX_NCM_NBS_CCT_LOOKUP ON RTC_NCM_CCLASSTRIB (NCM_NBS, REGRA, PARTICIPANTE);


CREATE TABLE RTC_OPERACOES_PRODUTO (
  ID 		INTEIRO,  
  OPERACOES INTEIRO NOT NULL,
  PRODUTO   INTEIRO NOT NULL,
  CCLASSTRIB  RTC_CCLASSTRIB_C NOT NULL,
  
  CONSTRAINT PK_RTC_OPERACOES_PRODUTO PRIMARY KEY (ID) USING INDEX PK_RTC_OPERACOES_PRODUTO, 
  CONSTRAINT UNQ_RTC_OPERACOES_PRODUTO UNIQUE (OPERACOES,PRODUTO), 
  CONSTRAINT FK_RTC_OPERACOES_PRODUTO_OPERACOES FOREIGN KEY (OPERACOES) REFERENCES RTC_OPERACOES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RTC_OPERACOES_PRODUTO_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES ITENS(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RTC_OPERACOES_PRODUTO_CCLASSTRIB FOREIGN KEY (CCLASSTRIB) REFERENCES RTC_CCLASSTRIB(CCLASSTRIB) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE ITENS ADD RTC_REGRA VCDESCRICAO50;



/* =========================
   3) Funções utilitárias
   ========================= */
CREATE OR ALTER FUNCTION RTC_VALIDAR_VIGENCIA(
  P_DATA_EMISSAO DT,
  P_DINIVIG      DT,
  P_DFIMVIG      DT
) RETURNS SMALL
AS
BEGIN
  IF ((P_DINIVIG IS NOT NULL) AND (P_DATA_EMISSAO < P_DINIVIG)) THEN RETURN 0;
  IF ((P_DFIMVIG IS NOT NULL) AND (P_DATA_EMISSAO > P_DFIMVIG)) THEN RETURN 0;
  RETURN 1;
END;

CREATE OR ALTER FUNCTION RTC_VALIDAR_MODELO(
  P_MODELO_DF CSIGLA10,
  P_IND_NFE   SMALL,
  P_IND_NFCE  SMALL,
  P_IND_NFSE  SMALL
) RETURNS SMALL
AS
DECLARE VARIABLE V_MODO CSIGLA10;
BEGIN
  V_MODO = UPPER(P_MODELO_DF);
  IF (V_MODO = 'NFE'  AND COALESCE(P_IND_NFE,  0)=1) THEN RETURN 1;
  IF (V_MODO = 'NFCE' AND COALESCE(P_IND_NFCE, 0)=1) THEN RETURN 1;
  IF (V_MODO = 'NFSE' AND COALESCE(P_IND_NFSE, 0)=1) THEN RETURN 1;
  RETURN 0;
END;

/* =========================
   4) Auxiliar de validação
   ========================= */
SET TERM ^ ;
CREATE OR ALTER PROCEDURE RTC_VALIDAR_CCLASSTRIB (
    P_CCLASSTRIB   RTC_CCLASSTRIB_C,
    P_DATA_EMISSAO DT,
    P_MODELO_DF    CSIGLA10
)
RETURNS (
    R_OK       SMALL,      -- 1 válido, 0 inválido
    R_CST      RTC_CST_C,
    R_PREDIBS  RTC_PERCENTUAL,
    R_PREDCBS  RTC_PERCENTUAL
)
AS
DECLARE VARIABLE V_DINI     DT;
DECLARE VARIABLE V_DFIM     DT;
DECLARE VARIABLE V_IND_NFE  SMALL;
DECLARE VARIABLE V_IND_NFCE SMALL;
DECLARE VARIABLE V_IND_NFSE SMALL;
BEGIN
  R_OK = 0; R_CST = NULL; R_PREDIBS = NULL; R_PREDCBS = NULL;

  SELECT DINIVIG, DFIMVIG, IND_NFE, IND_NFCE, IND_NFSE, PREDIBS, PREDCBS
    FROM RTC_CCLASSTRIB
   WHERE CCLASSTRIB = :P_CCLASSTRIB
    INTO :V_DINI, :V_DFIM, :V_IND_NFE, :V_IND_NFCE, :V_IND_NFSE, :R_PREDIBS, :R_PREDCBS;

  IF ( RTC_VALIDAR_VIGENCIA(:P_DATA_EMISSAO, :V_DINI, :V_DFIM) = 1
       AND RTC_VALIDAR_MODELO(:P_MODELO_DF, :V_IND_NFE, :V_IND_NFCE, :V_IND_NFSE) = 1 ) THEN
  BEGIN
    R_OK  = 1;
    R_CST = SUBSTRING(P_CCLASSTRIB FROM 1 FOR 3);
  END

  SUSPEND;
END^
SET TERM ; ^

/* =========================
   5) Procedure para obter o cClassTrib correto
   ========================= */
SET TERM ^ ;
CREATE OR ALTER PROCEDURE RTC_RESOLVER_CCLASSTRIB (
    P_ID_RTC_OPERACOES INTEIRO,
    P_ID_PRODUTO   INTEIRO,
    P_DATA_EMISSAO DT,
    P_MODELO_DF    CSIGLA10,
    P_ID_PARTICIPANTE INTEIRO 
)
RETURNS (
    R_CCLASSTRIB   RTC_CCLASSTRIB_C,   -- pode ser NULL se nada casar
    R_CST          RTC_CST_C,
    R_FONTE        VCDESCRICAO20,  -- 'RTC_OPERACOES' | 'RTC_OPERACOES_PRODUTO' |  'PRODUTO' | 'NCM_PARTICIPANTE' | 'NBS_PARTICIPANTE' | 'NCM' | 'NBS' | 'NONE'
    R_PREDIBS      RTC_PERCENTUAL,
    R_PREDCBS      RTC_PERCENTUAL
)
AS
DECLARE VARIABLE V_IDP INTEIRO;
DECLARE VARIABLE V_CCT_CAND   RTC_CCLASSTRIB_C;
DECLARE VARIABLE V_FONTE_CAND VCDESCRICAO20;
DECLARE VARIABLE V_OK         SMALL;
DECLARE VARIABLE V_CST_TMP    RTC_CST_C;
DECLARE VARIABLE V_RED_IBS    RTC_PERCENTUAL;
DECLARE VARIABLE V_RED_CBS    RTC_PERCENTUAL;
BEGIN
  R_CCLASSTRIB = NULL; R_CST = NULL; R_FONTE = 'NONE';
  R_PREDIBS = NULL; R_PREDCBS = NULL;
    -- se não vier informado o Tipo de Participante, tratamos como genérico (1)
  V_IDP = COALESCE(:P_ID_PARTICIPANTE, 1);

  FOR
    SELECT CCT, FONTE
    FROM (
      SELECT t.CCLASSTRIB AS CCT, 'RTC_OPERACOES' AS FONTE, 1 AS ORD
        FROM RTC_OPERACOES t
       WHERE t.ID = :P_ID_RTC_OPERACOES AND t.CCLASSTRIB IS NOT NULL

      UNION ALL

      SELECT tp.CCLASSTRIB AS CCT, 'RTC_OPERACOES_PRODUTO' AS FONTE, 2 AS ORD
        FROM RTC_OPERACOES_PRODUTO tp
       WHERE tp.OPERACOES = :P_ID_RTC_OPERACOES AND tp.PRODUTO = :P_ID_PRODUTO

      UNION ALL      

      SELECT r.CCLASSTRIB AS CCT, TIPO||TIPO||iif(:P_ID_PARTICIPANTE <> 1,'_PARTICIPANTE','') AS FONTE, 4 AS ORD
        FROM ITENS p
        JOIN RTC_NCM_CCLASSTRIB r ON r.NCM_NBS = p.NCM
         AND r.REGRA = p.RTC_REGRA
         AND :P_ID_PARTICIPANTE IS NOT DISTINCT FROM r.PARTICIPANTE
       WHERE p.CODIGO = :P_ID_PRODUTO

      UNION ALL      

      SELECT r.CCLASSTRIB AS CCT, TIPO AS FONTE, 5 AS ORD
        FROM ITENS p
        JOIN RTC_NCM_CCLASSTRIB r ON r.NCM_NBS = p.NCM AND r.REGRA = p.RTC_REGRA AND r.PARTICIPANTE = 1
       WHERE p.CODIGO = :P_ID_PRODUTO
    )
    ORDER BY ORD
    INTO :V_CCT_CAND, :V_FONTE_CAND
  DO
  BEGIN
    EXECUTE PROCEDURE RTC_VALIDAR_CCLASSTRIB(:V_CCT_CAND, :P_DATA_EMISSAO, :P_MODELO_DF)
      RETURNING_VALUES :V_OK, :V_CST_TMP, :V_RED_IBS, :V_RED_CBS;

    IF (V_OK = 1) THEN
    BEGIN
      R_CCLASSTRIB = V_CCT_CAND;
      R_CST        = V_CST_TMP;
      R_FONTE      = V_FONTE_CAND;
      R_PREDIBS    = V_RED_IBS;
      R_PREDCBS    = V_RED_CBS;
      SUSPEND;
      EXIT;  -- primeiro válido
    END
  END

  -- nada aplicável: devolve NULL e o chamador decide
  SUSPEND;
END^
SET TERM ; ^

/* =========================
   6) Procura cClassTrib por NCM_NBS
   ========================= */
SET TERM ^ ;
CREATE OR ALTER PROCEDURE RTC_CCLASSTRIB_POR_NCM_NBS (
    P_NCM_NBS RTC_NCM_NBS_C,
    P_ID_PARTICIPANTE INTEIRO
)
RETURNS (
    R_REGRA_RTC VCDESCRICAO50,
    R_CCLASSTRIB RTC_CCLASSTRIB_C,
    R_CST RTC_CST_C,
    R_PREDIBS RTC_PERCENTUAL,
    R_PREDCBS RTC_PERCENTUAL,
    R_VIGENCIA_INI DT,
    R_VIGENCIA_FIM DT,
    R_LC_REDACAO BLOB SUB_TYPE TEXT
)
AS
DECLARE VARIABLE V_IDP INTEIRO;
DECLARE VARIABLE V_OK SMALL;
DECLARE VARIABLE V_CST_TMP RTC_CST_C;
DECLARE VARIABLE V_RED_IBS RTC_PERCENTUAL;
DECLARE VARIABLE V_RED_CBS RTC_PERCENTUAL;
BEGIN
  V_IDP = COALESCE(:P_ID_PARTICIPANTE, 1);
  FOR
    SELECT 
      r.REGRA,
      r.CCLASSTRIB,
      o.DINIVIG,
      o.DFIMVIG,
      o.PREDIBS,
      o.PREDCBS,
      o.LC_REDACAO
    FROM RTC_NCM_CCLASSTRIB r
    LEFT JOIN RTC_CCLASSTRIB o ON o.CCLASSTRIB = r.CCLASSTRIB
    WHERE r.NCM_NBS = :P_NCM_NBS AND r.PARTICIPANTE = :V_IDP
    ORDER BY COALESCE(r.REGRA, ''), r.CCLASSTRIB
    INTO :R_REGRA_RTC, :R_CCLASSTRIB, :R_VIGENCIA_INI, :R_VIGENCIA_FIM, :R_PREDIBS, :R_PREDCBS, :R_LC_REDACAO
  DO
  BEGIN
    -- Determina o CST e valida (opcional)
    EXECUTE PROCEDURE RTC_VALIDAR_CCLASSTRIB(:R_CCLASSTRIB, CURRENT_DATE, 'NFe')
      RETURNING_VALUES :V_OK, :V_CST_TMP, :V_RED_IBS, :V_RED_CBS;

    R_CST = :V_CST_TMP;

    SUSPEND;
  END
END^
SET TERM ; ^

COMMIT;




